const nricCodes = [{
    'regionCode': '1',
    'townshipCodes': [
        'AGaya',
        'BaMaNa',
        'DaHpaYa',
        'HaPaNa',
        'HpaKaNa',
        'HsaBaTa',
        'HsaDaNa',
        'HsaLaNa',
        'HsaPaBa',
        'KaMaNa',
        'KaMaTa',
        'KaPaTa',
        'KhaBaDa',
        'KhaHpaNa',
        'KhaLaHpa',
        'LaGaNa',
        'MaKaNa',
        'MaKaTa',
        'MaKhaBa',
        'MaLaNa',
        'MaMaNa',
        'MaNjaNa',
        'MaSaNa',
        'NaMaNa',
        'PaNaDa',
        'PaTaA',
        'PaWaNa',
        'RaBaYa',
        'RaKaNa',
        'TaNaNa',
        'WaMaNa'
    ]
}, {
    'regionCode': '2',
    'townshipCodes': [
        'BaLaKha',
        'DaMaHsa',
        'HpaHsaNa',
        'HpaRaHsa',
        'LaKaNa',
        'MaSaNa',
        'RaTaNa',
        'RaThaNa',
    ]
}, {
    'regionCode': '3',
    'townshipCodes': [
        'BaANa',
        'BaGaLa',
        'BaThaHsa',
        'HpaPaNa',
        'KaDaNa',
        'KaHsaKa',
        'KaKaRa',
        'KaMaMa',
        'LaBaNa',
        'LaThaNa',
        'MaWaTa',
        'PaKaNa',
        'RaRaTha',
        'SaKaLa',
        'ThaTaKa',
        'ThaTaNa',
        'WaLaMa'
    ]
}, {
    'regionCode': '4',
    'townshipCodes': [
        'HaKhaNa',
        'HpaLaNa',
        'HsaMaNa',
        'HtaTaLa',
        'KaKhaNa',
        'KaPaLa',
        'MaTaNa',
        'MaTaPa',
        'PaLaWa',
        'RaKhaDa',
        'RaZaNa',
        'TaTaNa',
        'TaZaNa'
    ]
}, {
    'regionCode': '5',
    'townshipCodes': [
        'ARaTa',
        'ATaNa',
        'BaMaNa',
        'BaTaLa',
        'DaHaNa',
        'DaPaYa',
        'HaMaLa',
        'HpaPaNa',
        'HsaLaKa',
        'HsaMaRa',
        'HtaKhaNa',
        'HtaPaKha',
        'KaBaLa',
        'KaLaHta',
        'KaLaNa',
        'KaLaTa',
        'KaLaWa',
        'KaMaNa',
        'KaNaNa',
        'KaThaNa',
        'KhaPaNa',
        'KhaTaNa',
        'KhaUNa',
        'KhaUTa',
        'LaHaNa',
        'LaRaNa',
        'MaKaNa',
        'MaLaNa',
        'MaMaNa',
        'MaMaTa',
        'MaPaLa',
        'MaRaNa',
        'MaThaNa',
        'NaYaNa',
        'NgaZaNa',
        'PaHsaNa',
        'PaLaBa',
        'PaLaNa',
        'RaBaNa',
        'RaUNa',
        'SaKaNa',
        'TaHsaNa',
        'TaMaNa',
        'WaLaNa',
        'WaThaNa',
        'YaMaPa'
    ]
}, {
    'regionCode': '6',
    'townshipCodes': [
        'BaPaNa',
        'HtaWaNa',
        'KaLaA',
        'KaRaRa',
        'KaSaNa',
        'KaThaNa',
        'KhaMaKa',
        'LaLaNa',
        'MaANa',
        'MaARa',
        'MaMaNa',
        'MaTaNa',
        'PaKaMa',
        'PaLaNa',
        'PaLaTa',
        'RaHpaNa',
        'TaThaRa',
        'ThaRaKha'
    ]
}, {
    'regionCode': '7',
    'townshipCodes': [
        'AHpaNa',
        'ATaNa',
        'DaUNa',
        'HpaMaNa',
        'HtaTaPa',
        'KaKaNa',
        'KaPaKa',
        'KaTaKha',
        'KaWaNa',
        'LaPaTa',
        'MaLaNa',
        'MaNjaNa',
        'NaTaLa',
        'NjaLaPa',
        'PaKhaNa',
        'PaKhaTa',
        'PaMaNa',
        'PaTaNa',
        'PaTaTa',
        'RaKaNa',
        'RaTaNa',
        'RaTaRa',
        'TaNgaNa',
        'ThaKaNa',
        'ThaNaPa',
        'ThaWaTa',
        'WaMaNa',
        'ZaKaNa'
    ]
}, {
    'regionCode': '8',
    'townshipCodes': [
        'ALaNa',
        'GaGaNa',
        'HsaHpaNa',
        'HsaMaNa',
        'HsaPaWa',
        'HtaLaNa',
        'KaHtaNa',
        'KaMaNa',
        'KhaMaNa',
        'MaBaNa',
        'MaHtaNa',
        'MaKaNa',
        'MaLaNa',
        'MaMaNa',
        'MaTaNa',
        'MaThaNa',
        'NaMaNa',
        'NgaHpaNa',
        'PaHpaNa',
        'PaKhaKa',
        'PaMaNa',
        'RaNaKha',
        'RaSaKa',
        'SaLaNa',
        'SaTaRa',
        'TaTaKa',
        'ThaRaNa'

    ]
}, {
    'regionCode': '9',
    'townshipCodes': [
        'AMaYa',
        'AMaZa',
        'DaKhaTha',
        'KaHsaNa',
        'KaPaTa',
        'KhaAZa',
        'KhaMaSa',
        'LaWaNa',
        'MaHaMa',
        'MaHtaLa',
        'MaKaNa',
        'MaKhaNa',
        'MaLaNa',
        'MaMaNa',
        'MaNaMa',
        'MaNaTa',
        'MaRaMa',
        'MaRaTa',
        'MaTaRa',
        'MaThaNa',
        'NaHtaKa',
        'NgaThaRa',
        'NgaZaNa',
        'NjaUNa',
        'PaBaNa',
        'PaBaTha',
        'PaKaKha',
        'PaMaNa',
        'PaMaNa',
        'PaULa',
        'RaMaTha',
        'SaKaNa',
        'SaKaTa',
        'TaKaNa',
        'TaKaTa',
        'TaTaU',
        'TaThaNa',
        'ThaPaKa',
        'ThaSaNa',
        'UTaTha',
        'WaTaNa',
        'ZaBaTha',
        'ZaYaTha'
    ]
}, {
    'regionCode': '10',
    'townshipCodes': [
        'BaLaNa',
        'KaHtaNa',
        'KaMaRa',
        'KhaHsaNa',
        'KhaZaNa',
        'LaMaNa',
        'MaDana',
        'MaLaMa',
        'PaMaNa',
        'RaMaNa',
        'ThaHpaRa',
        'ThaHtaNa'
    ]
}, {
    'regionCode': '11',
    'townshipCodes': [
        'AMaNa',
        'BaThaTa',
        'GaMaNa',
        'KaHpaNa',
        'KaTaLa',
        'KaTaNa',
        'MaANa',
        'MaATa',
        'MaPaNa',
        'MaPaTa',
        'MaTaNa',
        'MaUNa',
        'PaNaKa',
        'PaTaNa',
        'RaBaNa',
        'RaThaTa',
        'SaTaNa',
        'TaKaNa',
        'TaPaWa',
        'ThaTaNa'
    ]
}, {
    'regionCode': '12',
    'townshipCodes': [
        'ALaNa',
        'ASaNa',
        'BaHaNa',
        'BaTaHta',
        'DaGaHsa',
        'DaGaMa',
        'DaGaNa',
        'DaGaRa',
        'DaGaTa',
        'DaLaNa',
        'DaPaNa',
        'HsaKaKha',
        'HsaKaNa',
        'HtaTaPa',
        'KaKaKa',
        'KaKhaKa',
        'KaMaNa',
        'KaMaRa',
        'KaMaTa',
        'KaTaNa',
        'KaTaTa',
        'KhaRaNa',
        'LaKaNa',
        'LaMaNa',
        'LaMaTa',
        'LaThaNa',
        'LaThaYa',
        'LaYaNa',
        'LaYaRa',
        'MaBaNa',
        'MaGaDa',
        'MaGaTa',
        'MaRaKa',
        'PaBaTa',
        'PaZaTa',
        'RaKaNa',
        'RaPaTha',
        'SaKhaNa',
        'TaKaNa',
        'TaMaNa',
        'TaTaNa',
        'TaTaTa',
        'ThaGaKa',
        'ThaKaTa',
        'ThaKhaNa',
        'ThaLaNa',
        'UKaMa',
        'UKaTa'

    ]
}, {
    'regionCode': '13',
    'townshipCodes': [
        'ATaNa',
        'HaMaNa',
        'HaPaNa',
        'HaPaTa',
        'HpaKhaNa',
        'HsaHsaNa',
        'KaHaNa',
        'KaKaNa',
        'KaKhaNa',
        'KaLaDa',
        'KaLaHta',
        'KaLaNa',
        'KaLaTa',
        'KaMaNa',
        'KaTaLa',
        'KaTaNa',
        'KaTaTa',
        'KaThaNa',
        'KhaLaNa',
        'KhaRaHa',
        'LaKaNa',
        'LaKhaNa',
        'LaKhaTa',
        'LaLaNa',
        'LaRaNa',
        'MaBaNa',
        'MaHaRa',
        'MaHpaNa',
        'MaHpaTa',
        'MaHsaNa',
        'MaHsaTa',
        'MaHtaNa',
        'MaHtaTa',
        'MaKaHta',
        'MaKaNa',
        'MaKaTa',
        'MaKhaNa',
        'MaKhaTa',
        'MaLaNa',
        'MaLaTa',
        'MaMaHta',
        'MaMaNa',
        'MaMaTa',
        'MaNaNa',
        'MaNaTa',
        'MaNgaNa',
        'MaPaHta',
        'MaPaNa',
        'MaPaTa',
        'MaRaNa',
        'MaRaTa',
        'MaSaNa',
        'MaTaNa',
        'MaTaTa',
        'MaYaHta',
        'MaYaNa',
        'MaYaTa',
        'NaHpaNa',
        'NaHsaNa',
        'NaKhaNa',
        'NaKhaTa',
        'NaMaTa',
        'NaSaNa',
        'NaTaNa',
        'NaTaRa',
        'NjaRaNa',
        'PaHsaNa',
        'PaHsaTa',
        'PaLaHta',
        'PaLaNa',
        'PaLaTa',
        'PaPaKa',
        'PaTaYa',
        'PaWaNa',
        'PaYaNa',
        'RaNgaNa',
        'RaSaNa',
        'TaKaNa',
        'TaKhaLa',
        'TaLaNa',
        'TaMaNja',
        'TaTaNa',
        'TaYaNa',
        'ThaNaNa',
        'ThaPaNa'

    ]
}, {
    'regionCode': '14',
    'townshipCodes': [
        'AGaPa',
        'AMaNa',
        'AMaTa',
        'BaKaLa',
        'DaDaYa',
        'DaNaHpa',
        'HaKaKa',
        'HaThaTa',
        'HpaPaNa',
        'KaKaHta',
        'KaKaNa',
        'KaKhaNa',
        'KaLaNa',
        'KaPaNa',
        'LaMaNa',
        'LaPaTa',
        'MaANa',
        'MaAPa',
        'MaMaKa',
        'MaMaNa',
        'NgaHsaNa',
        'NgaPaTa',
        'NgaRaKa',
        'NgaThaKha',
        'NjaTaNa',
        'PaSaLa',
        'PaTaNa',
        'PaThaNa',
        'PaThaRa',
        'RaKaNa',
        'RaThaYa',
        'ThaPaNa',
        'WaKhaMa',
        'ZaLaNa',

    ]
},
];

function getTownShipCode(nric_region_code) {
    return nricCodes.find(code => code.regionCode === nric_region_code);
}

module.exports = getTownShipCode